version: '3.9'

services:
    frankenphp:
        container_name: frankenphp-container
        build:
            context: .
            dockerfile: dockerfile
        ports:
            - 80:80
            - 443:443
            - 443:443/udp
        volumes:
            - $PWD:/app

    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: frankenphp
            POSTGRES_PASSWORD: frankenphp
            POSTGRES_DB: frankenphp
        ports:
            - 5432:5432
        volumes:
            - frankenphp-db:/var/lib/postgresql/data

    adminer:
        image: adminer
        ports:
            - 8080:8080

volumes:
  frankenphp-db: